import Head from "next/head";
import HomeComponent from "@/components/Home/index";
import Styles from "./Main.module.scss";


export default function Home() {
  return (
    <>
      <Head>
        <title>Data Doodle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Styles.main}>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <HomeComponent />
        </div>
      </main>
    </>
  );
}
